{
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "aSTBcEisBId1ZG0uuHgm8H/HGswO5iHeHtF/8P3tsFqv57ZrBBUkzurYBRgnGUCrkf\u002BoMcLqhvR\u002BCeK/jtQkK/yaVDtG9bboJmQyX/KWsMlQ9n5IDOj94hFfCAeenkUwZ\u002Bs78rYJCnMYR98u6aru5EXYQFYS8Ilvch8V3ryYac4="
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "stage" : "test"
         },
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "notifications" : {
      "email" : [
         "wakaba@suikawiki.org"
      ],
      "irc" : {
         "channels" : [
            "ircs://irc.suikawiki.org:6697#mechanize"
         ],
         "use_notice" : true
      }
   },
   "perl" : [
      "5.26",
      "5.14",
      "5.10"
   ],
   "script" : "make test"
}
