perl:
  - "5.16"
  - "5.10"
before_install: git submodule update --init
install: "make test-deps"
script: "make test && ./perl t/parsing.t"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "suika.fam.cx#mechanize"
    use_notice: true
